---
title: "IdeaVictor"
author: "Christian Castro"
date: "08-12-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r pressure, echo=FALSE}

library(ggplot2)
library(ggpubr)
library(markdown)
library(shiny)
library(shinythemes)
library(tidyverse)
library(magrittr)
library(lubridate)
library(plotly)
library(xts)
library(dygraphs)
library(kableExtra)
library(knitr)
library("readxl")
library(rsconnect)
library(dplyr)
library(summarytools)
library(epiDisplay)
#library(leaflet)
library(haven)
library(epiDisplay)
library("readxl")
library(expss)
library(hrbrthemes)
library(viridis)
library(viridisLite)
library(DescTools)
library(roperators)
library(shinycssloaders)
library(writexl)
library(vroom)
library(shinyWidgets)
library(stringr)
library(dplyr)
library(gapminder)
library(tidyverse)
library(moderndive)
library(skimr)

oldw <- getOption("warn")
options(warn = -1)

dataset2006  <- readRDS("dataset2006.rds")
dataset2009  <- readRDS("dataset2009.rds")
dataset2011  <- readRDS("dataset2011.rds")
dataset2013  <- readRDS("dataset2013.rds")
dataset2015  <- readRDS("dataset2015.rds")
dataset2017  <- readRDS("dataset2017.rds")

```


### 2006

```{r}


    ab <- dataset2006

    data_code <- ab[  , c("seg", "comuna")]
    names(data_code)[2] <- "unlist.a."
    data_code <- distinct(data_code , unlist.a., .keep_all = TRUE)

    # https://stackoverflow.com/questions/22337394/dplyr-mutate-with-conditional-values/22337459

    data_code  <-  data_code  %>% mutate(codigo = case_when(as.integer(seg / 10000000) == 0 ~ as.integer(seg / 1000)
                                                            , as.integer(seg / 10000000) == 1 ~ as.integer(seg / 1000)
    ))

    data_code <- subset( data_code, select = -seg )

    data_code[270,2]<-11201
    data_code[8,2]<-15101
    data_code[178,2]<-16102
    data_code[9,2]<-15102
    data_code[2,2]<-1402
    data_code[177,2]<-16101
    data_code[182,2]<-16103
    data_code[96,2]<-6303
    data_code[179,2]<-16202
    data_code[180,2]<-16203
    data_code[181,2]<-16302
    data_code[3,2]<-1403
    data_code[287,2]<-13104
    data_code[261,2]<-14102
    data_code[183,2]<-16104
    data_code[262,2]<-14202
    data_code[11,2]<-15202
    data_code[4,2]<-1404
    data_code[292,2]<-13110
    data_code[263,2]<-14201
    data_code[264,2]<-14203
    data_code[265,2]<-14103
    data_code[66,2]<-5802
    data_code[266,2]<-14104
    data_code[267,2]<-14105
    data_code[268,2]<-14106
    data_code[89,2]<-6110
    data_code[184,2]<-16204
    data_code[185,2]<-16303
    data_code[68,2]<-5803
    data_code[271,2]<-14107
    data_code[272,2]<-14108
    data_code[186,2]<-16105
    data_code[5,2]<-1405
    data_code[187,2]<-16106
    data_code[188,2]<-16205
    data_code[6,2]<-1401
    data_code[10,2]<-15201
    data_code[246,2]<-16107
    data_code[49,2]<-5801
    data_code[92,2]<-6114
    data_code[190,2]<-16201
    data_code[191,2]<-16206
    data_code[273,2]<-14204
    data_code[192,2]<-16301
    data_code[193,2]<-16304
    data_code[194,2]<-16108
    data_code[195,2]<-16305
    data_code[286,2]<-13505
    data_code[196,2]<-16207
    data_code[260,2]<-14101
    data_code[51,2]<-5804
    data_code[197,2]<-16109

    a <- ab$comuna
    b <- ab$ytotaj
    c <- ab$t4
    d <- ab$sexo

    cross_tab =  xtabs(ab$expc ~ unlist(a) + unlist(b)+unlist(c)+unlist(d),aggregate(ab$expc ~ unlist(a)+unlist(b)+unlist(c)+unlist(d),ab,mean))

    tabla <- as.data.frame(cross_tab)

    d <-tabla[!(tabla$Freq == 0),]

    d$anio <- "2006"

    df = merge( x = d, y = data_code, by = "unlist.a.", all.x = TRUE)
    write.csv(df,"tabla_023_etnia_2006.csv", row.names = FALSE)


```
### 2009

```{r}

    ab <- dataset2009

    data_code <- ab[  , c("segmento", "comuna")]

    names(data_code)[2] <- "unlist.a."
    data_code <- distinct(data_code , unlist.a., .keep_all = TRUE)

    data_code <- data_code %>% mutate(unlist.a. = str_squish(unlist.a.))

    data_code  <-  data_code  %>% mutate(codigo = case_when(as.integer(segmento / 10000000) == 0 ~ as.integer(segmento  / 1000)
                                                            , as.integer(segmento  / 10000000) == 1 ~ as.integer(segmento / 1000)

    ))

    data_code <- subset( data_code, select = -segmento )

    data_code[253,2]<-16102
    data_code[149,2]<-16101
    data_code[150,2]<-16103
    data_code[305,2]<-16202
    data_code[306,2]<-16203
    data_code[44,2]<-16302
    data_code[45,2]<-16104
    data_code[106,2]<-5802
    data_code[332,2]<-16204
    data_code[46,2]<-16303
    data_code[107,2]<-5803
    data_code[47,2]<-16105
    data_code[48,2]<-16106
    data_code[307,2]<-16205
    data_code[254,2]<-16107
    data_code[98,2]<-5801
    data_code[308,2]<-16201
    data_code[309,2]<-16206
    data_code[49,2]<-16301
    data_code[310,2]<-16304
    data_code[311,2]<-16108
    data_code[255,2]<-16305
    data_code[256,2]<-16207
    data_code[99,2]<-5804
    data_code[312,2]<-16109


    a <- ab$comuna
    b <- ab$ytotaj
    c <- ab$t5
    d <- ab$sexo



    cross_tab =  xtabs(ab$expc ~ unlist(a) + unlist(b)+unlist(c)+unlist(d),aggregate(ab$expc ~ unlist(a)+unlist(b)+unlist(c)+unlist(d),ab,mean))


    tabla <- as.data.frame(cross_tab)

    d <-tabla[!(tabla$Freq == 0),]

    d$anio <- "2009"

    df = merge( x = d, y = data_code, by = "unlist.a.", all.x = TRUE)

    write.csv(df,"tabla_023_2009.csv", row.names = FALSE)

```

2011

```{r}
ab  <- dataset2011

    data_code <- ab[ , c("segmento", "comuna")]

    names(data_code)[2] <- "a"
    data_code <- distinct(data_code , a, .keep_all = TRUE)
    data_code <- data_code %>% mutate(a = str_squish(a))


    data_code <- data_code %>% mutate(codigo = case_when(as.integer(segmento / 10000000) == 0 ~ as.integer(segmento/ 10000)
                                                         , as.integer(segmento / 10000000) <17 ~ as.integer(segmento / 10000)

    ))

    data_code <- subset( data_code, select = -segmento )
    data_code[171,2]<-16101
    data_code[172,2]<-16102
    data_code[173,2]<-16202
    data_code[174,2]<-16203
    data_code[175,2]<-16302
    data_code[176,2]<-16103
    data_code[177,2]<-16104
    data_code[178,2]<-16204
    data_code[179,2]<-16303
    data_code[180,2]<-16105
    data_code[181,2]<-16106
    data_code[182,2]<-16205
    data_code[183,2]<-16107
    data_code[184,2]<-16201
    data_code[185,2]<-16206
    data_code[186,2]<-16301
    data_code[187,2]<-16304
    data_code[188,2]<-16108
    data_code[189,2]<-16305
    data_code[190,2]<-16207
    data_code[191,2]<-16109

    a <- ab$comuna
    b <- ab$ytotaj
    c <- ab$r6
    d <- ab$sexo


    cross_tab =  xtabs(ab$expc_full ~ unlist(a) + unlist(b)+unlist(c)+unlist(d),aggregate(ab$expc_full ~ unlist(a)+unlist(b)+unlist(c)+unlist(d),ab,mean))

    tabla <- as.data.frame(cross_tab)

    d <-tabla[!(tabla$Freq == 0),]
    names(d)[1] <- "a"
    d$anio <- "2011"

    df = merge( x = d, y = data_code, by = "a", all.x = TRUE)
    write.csv(df,"tabla_023_etnia_2011.csv", row.names = FALSE)
```

2013

```{r}

    ab <- dataset2013


    a <- ab$comuna
    b <- ab$ytotcorh
    c <- ab$r6
    d <- ab$sexo


    cross_tab =  xtabs(ab$expc ~ unlist(a) + unlist(b)+unlist(c)+unlist(d),aggregate(ab$expc ~ unlist(a)+unlist(b)+unlist(c)+unlist(d),ab,mean))

    tabla <- as.data.frame(cross_tab)
    d <-tabla[!(tabla$Freq == 0),]
    d$anio <- "2013"

    data_code <- ab[  , c("folio", "comuna")]

    names(data_code)[2] <- "a"
    data_code <- distinct(data_code , a, .keep_all = TRUE)

    data_code <- data_code %>% mutate(a = str_squish(a))

    data_code <- data_code %>% mutate(codigo = case_when(as.integer(folio / 10000000000) == 0 ~ as.integer(folio/ 10000000)
                                                         , as.integer(folio / 10000000000) <17 ~ as.integer(folio / 10000000)

    ))

    data_cod <- subset( data_code, select = -folio )
    data_cod[171,2]<-16101
    data_cod[172,2]<-16102
    data_cod[173,2]<-16202
    data_cod[174,2]<-16203
    data_cod[175,2]<-16302
    data_cod[176,2]<-16103
    data_cod[177,2]<-16104
    data_cod[178,2]<-16204
    data_cod[179,2]<-16303
    data_cod[180,2]<-16105
    data_cod[181,2]<-16106
    data_cod[182,2]<-16205
    data_cod[183,2]<-16107
    data_cod[184,2]<-16201
    data_cod[185,2]<-16206
    data_cod[186,2]<-16301
    data_cod[187,2]<-16304
    data_cod[188,2]<-16108
    data_cod[189,2]<-16305
    data_cod[190,2]<-16207
    data_cod[191,2]<-16109
    names(d)[1] <- "a"

    df = merge( x = d, y = data_cod, by = "a", all.x = TRUE)

    write.csv(df,"tabla_023_etnia_2013.csv", row.names = FALSE)
```

## 2015

```{r}
 
    ab <- dataset2015
    
    a <- ab$comuna
    b <- ab$ytot
    c <- ab$r3
    d <- ab$sexo
    
    cross_tab =  xtabs(ab$expc ~ unlist(a) + unlist(b)+unlist(c)+unlist(d),aggregate(ab$expc ~ unlist(a)+unlist(b)+unlist(c)+unlist(d),ab,mean))
    
    tabla <- as.data.frame(cross_tab)
    d <-tabla[!(tabla$Freq == 0),]
    d$anio <- "2015"
    
    data_code <- ab[  , c("folio", "comuna")]
    
    names(data_code)[2] <- "a"
    data_code <- distinct(data_code , a, .keep_all = TRUE)
    
    data_code <- data_code %>% mutate(a = str_squish(a))
    
    data_code <- data_code %>% mutate(codigo = case_when(as.integer(folio / 10000000000) == 0 ~ as.integer(folio/ 10000000)
                                                         , as.integer(folio / 10000000000) <17 ~ as.integer(folio / 10000000)
                                                         
    ))
    
    data_cod <- subset( data_code, select = -folio )
    data_cod[171,2]<-16101
    data_cod[172,2]<-16102
    data_cod[173,2]<-16202
    data_cod[174,2]<-16203
    data_cod[175,2]<-16302
    data_cod[176,2]<-16103
    data_cod[177,2]<-16104
    data_cod[178,2]<-16204
    data_cod[179,2]<-16303
    data_cod[180,2]<-16105
    data_cod[181,2]<-16106
    data_cod[182,2]<-16205
    data_cod[183,2]<-16107
    data_cod[184,2]<-16201
    data_cod[185,2]<-16206
    data_cod[186,2]<-16301
    data_cod[187,2]<-16304
    data_cod[188,2]<-16108
    data_cod[189,2]<-16305
    data_cod[190,2]<-16207
    data_cod[191,2]<-16109
    
    names(d)[1] <- "a"
    
    df = merge( x = d, y = data_cod, by = "a", all.x = TRUE)
    
    write.csv(df,"tabla_023_etnia_2015.csv", row.names = FALSE)
```

# 2017

```{r}
    ab <- dataset2017
    
    a <- ab$comuna
    b <- ab$ytot
    c <- ab$r3
    d <- ab$sexo

    cross_tab =  xtabs(ab$expc ~ unlist(a) + unlist(b)+unlist(c)+unlist(d),aggregate(ab$expc ~ unlist(a)+unlist(b)+unlist(c)+unlist(d),ab,mean))
    
    tabla <- as.data.frame(cross_tab)
    d <-tabla[!(tabla$Freq == 0),]
    d$anio <- "2017"
    
    data_code <- ab[  , c("folio", "comuna")]
    
    names(data_code)[2] <- "a"
    data_code <- distinct(data_code , a, .keep_all = TRUE)
    #
    data_code <- data_code %>% mutate(a = str_squish(a))
    
    data_code <- data_code %>% mutate(codigo = case_when(as.integer(folio / 1000000000000) == 0 ~ as.integer(folio/ 100000000)
                                                         , as.integer(folio / 1000000000000) <17 ~ as.integer(folio / 100000000)
                                                         
    ))
    
    data_cod <- subset( data_code, select = -folio )
    
    data_cod[172,2]<-16102
    data_cod[171,2]<-16101
    data_cod[176,2]<-16103
    data_cod[173,2]<-16202
    data_cod[174,2]<-16203
    data_cod[175,2]<-16302
    data_cod[177,2]<-16104
    data_cod[178,2]<-16204
    data_cod[179,2]<-16303
    data_cod[180,2]<-16105
    data_cod[181,2]<-16106
    data_cod[182,2]<-16205
    data_cod[183,2]<-16107
    data_cod[184,2]<-16201
    data_cod[185,2]<-16206
    data_cod[186,2]<-16301
    data_cod[187,2]<-16304
    data_cod[188,2]<-16108
    data_cod[189,2]<-16305
    data_cod[190,2]<-16207
    data_cod[191,2]<-16109
    
    names(d)[1] <- "a"
    
    df = merge( x = d, y = data_cod, by = "a", all.x = TRUE)
    
    write.csv(df,"tabla_023_etnia_2017.csv", row.names = FALSE)
```






Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
